# This playbook wakes up all/selected desktop system.

- hosts: energy_wake
  gather_facts: no
  #become: yes
  vars:
    mac: "d4:85:64:c9:26:10"

  tasks:
  #- name: "List facts"
  #  ansible.builtin.debug:
  #    var: ansible_facts
  - name: "look for host in arp table history"
    shell: arp |grep C |grep eth0 |awk '{print $3}' |head -n 1  #old connection
    register: wolmacaddress
    ignore_errors: True

  - debug:
      var: mac

  - name: "wake remote host from arp table"
    shell: etherwake '{{ wolmacaddress.stdout }}'
    ignore_errors: True
    when: wolmacaddress.stdout is defined

  - name: "wake remote host from inventorized mac addres"
    shell: etherwake '{{ mac }}'
    ignore_errors: True
    #changed_when: "'FAILED' not in wolmacaddress.stdout"

    #- hosts: energy-pool
    #  gather_facts: no
    #  tags: test
    #  tasks:
    #  - name: Wait for the system's service to come online
    #    wait_for_connection:
    #      timeout: 30
