# This playbook wakes up all/selected desktop system.

- hosts: energy_wake
#  gather_facts: no
  vars:
    macaddress: "d4:85:64:c9:26:10"

  tasks:
  - name: "Wake remote host"
    ansible.builtin.debug:
      var: ansible_facts
    #shell: etherwake '{{ macaddress }}'

    #- hosts: energy-pool
    #  gather_facts: no
    #  tags: test
    #  tasks:
    #  - name: Wait for the system's service to come online
    #    wait_for_connection:
    #      timeout: 30
