# This playbook wakes up all/selected desktop system.

- hosts: energy_wake
  gather_facts: no
  #become: yes
  vars:
    macaddress: "d4:85:64:c9:26:10"

  tasks:
  #- name: "List facts"
  #  ansible.builtin.debug:
  #    var: ansible_facts
  - name: "look for host"
    shell: arp |grep C |grep eth0 |awk '{print $3}' |head -n 1  #old connection
    register: wolmacaddress
    ignore_errors: True

  - name: "wake remote host"
    shell: etherwake '{{ wolmacaddress.stdout }}'
    when: wolmacaddress is success

  - set_fact:
      waladdr: "{{ wolmacaddress.stdout }}"
  - debug:
      var: waladdr
      
      
    #- hosts: energy-pool
    #  gather_facts: no
    #  tags: test
    #  tasks:
    #  - name: Wait for the system's service to come online
    #    wait_for_connection:
    #      timeout: 30
